### ISSUE TITLE
missing mei.h

### ISSUE THREAD

**Issue by cfasnacht** [mjg59/mei-amt-check#12]
Thanks for you tool, worked great for me on Ubuntu and Centos 7

On Centos 6, I encountered the following error:
make
gcc     mei-amt-check.c   -o mei-amt-check
mei-amt-check.c:78:23: error: linux/mei.h: No such file or directory
mei-amt-check.c:94: error: expected specifier-qualifier-list before ‘uuid_le’
mei-amt-check.c: In function ‘mei_deinit’:
mei-amt-check.c:104: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:105: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:106: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:107: error: ‘struct mei’ has no member named ‘buf_size’
mei-amt-check.c:108: error: ‘struct mei’ has no member named ‘prot_ver’
mei-amt-check.c:109: error: ‘struct mei’ has no member named ‘initialized’
mei-amt-check.c: At top level:
mei-amt-check.c:112: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
mei-amt-check.c: In function ‘mei_recv_msg’:
mei-amt-check.c:170: error: ‘struct mei’ has no member named ‘verbose’
mei-amt-check.c:172: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:178: error: ‘struct mei’ has no member named ‘verbose’
mei-amt-check.c: In function ‘mei_send_msg’:
mei-amt-check.c:194: error: ‘struct mei’ has no member named ‘verbose’
mei-amt-check.c:196: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:205: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:205: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:206: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:207: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:207: error: ‘struct mei’ has no member named ‘fd’
mei-amt-check.c:208: error: ‘struct mei’ has no member named ‘verbose’
mei-amt-check.c: At top level:
mei-amt-check.c:291: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘MEI_IAMTHIF’
mei-amt-check.c: In function ‘amt_host_if_init’:
mei-amt-check.c:335: error: ‘MEI_IAMTHIF’ undeclared (first use in this function)
mei-amt-check.c:335: error: (Each undeclared identifier is reported only once
mei-amt-check.c:335: error: for each function it appears in.)
mei-amt-check.c: In function ‘amt_host_if_call’:
mei-amt-check.c:415: error: ‘struct mei’ has no member named ‘buf_size’
make: *** [mei-amt-check] Error 1

Do you have any idea from where I get the mei.h?
Thanks in advance!

**Comment by mjg59** [comment]
You need a newer kernel, I'm afraid this won't work with CentOS 6.

**Comment by cfasnacht** [comment]
Ok thanks, may be you can add this and the required kernel version to the Readme, I guess I'm not the only one who stumbled on this.

Thanks
