### ISSUE TITLE
Cannot open /dev/mei0: No such file or directory

### ISSUE THREAD

**Issue by devhen** [mjg59/mei-amt-check#3]
I get:

[root@localhost mei-amt-check]# ./mei-amt-check 
Cannot open /dev/mei0: No such file or directory

To my knowledge this machine doesn't use AMT. I'm assuming this message is functionally equivalent to getting the "Intel AMT: DISABLED" output?

Thanks

**Comment by mjg59** [comment]
I believe that means the platform doesn't support AMT at all.

**Comment by d33tah** [comment]
@mjg59 or perhaps the kernel module is not loaded?

**Comment by rst** [comment]
On Ubuntu 14.04 LTS, I had to change this from "/dev/mei0" to "/dev/mei" in the source code.  The module was loaded (and showed up in "lsmod" output); it just was creating a device with a different name.

**Comment by rexberg** [comment]
@rst Yes, I can confirm this on a Ubuntu 16.04 LTS host.
